name: Run Scraper on Schedule

# Schedule the action to run daily at midnight
on:
  schedule:
    - cron: '0 0 * * *'  # This runs the script once a day at midnight (UTC)
  workflow_dispatch:    # Allows you to manually trigger the action as well

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper script
        run: python scraper.py
